// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM3D-xkT5wcU-TOWVqzMXUICR9w9c-w6E',
    appId: '1:279210645793:web:f423f0095e8cc42e6d4660',
    messagingSenderId: '279210645793',
    projectId: 'chatapp-339d8',
    authDomain: 'chatapp-339d8.firebaseapp.com',
    storageBucket: 'chatapp-339d8.appspot.com',
    measurementId: 'G-H1ESN2ZTTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjeZ9T7QNAX0Iw7skEwfa48jJU1crvrXo',
    appId: '1:279210645793:android:df6753c83c0e3f7a6d4660',
    messagingSenderId: '279210645793',
    projectId: 'chatapp-339d8',
    storageBucket: 'chatapp-339d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeUx0CN2QHAuh2n0IgL_4fu2eHW2XT6eg',
    appId: '1:279210645793:ios:0a46c1a452d887fe6d4660',
    messagingSenderId: '279210645793',
    projectId: 'chatapp-339d8',
    storageBucket: 'chatapp-339d8.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeUx0CN2QHAuh2n0IgL_4fu2eHW2XT6eg',
    appId: '1:279210645793:ios:cad1a6106b0878ce6d4660',
    messagingSenderId: '279210645793',
    projectId: 'chatapp-339d8',
    storageBucket: 'chatapp-339d8.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
